<?php

/**
 * @file
 * This is an example outlining how a module can be used to define a new
 * node type.
 *
 * (Note that custom node types are most often created with CCK in recent
 * versions of Drupal.)
 *
 * Our example node types will allow users to specify a "color" and a "quantity"
 * for their nodes; some kind of rudimentary inventory-tracking system, perhaps?
 * To store this extra information, we need an auxiliary database tabel as
 * defined in node_example_schema() in the node_example.install file.
 */

/**
 * @defgroup node_example Example: Node
 * @ingroup examples
 * @{
 * Creating a new content type in a module. (drupal6)
 *
 * This is an example outlining how a module can be used to define a new
 * node type.
 *
 * (Note that custom node types are most often created with CCK in recent
 * versions of Drupal.)
 *
 * Our example node types will allow users to specify a "color" and a "quantity"
 * for their nodes; some kind of rudimentary inventory-tracking system, perhaps?
 * To store this extra information, we need an auxiliary database tabel as
 * defined in node_example_schema() in the node_example.install file.
 *
 * This exmple is pare of the Examples for Developers Project which you can download
 * and experiment with here: http://drupal.org/project/examples
 */

 /**
  * Implements hook_menu().
  */
function node_example_menu() {
  $items['examples/node_example'] = array(
    'title'           => 'Node Example',
    'page callback'   => 'node_example_info',
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Page callback for path 'examples/node_example'
 */
function node_example_info() {
  return t('The node example defines a new node type, "Example node type 1"'
         . 'which can be created at !link.',
         array('!link' => l(t('node/add/example-node-type-1'),
               'node/add/example-node-type-1'))
          );
}

